// invert.idl : IDL source for invert.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (invert.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(E12EAE06-D0DD-404B-B168-4AAF09785AC0),
	version(1.0),
	helpstring("invert 1.0 Type Library")
]
library INVERTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

};
