CFLAGS=-O2 -Wall -I/usr/local/pgsql/include
LFLAGS=-L/usr/local/pgsql/lib -lmfl -lcrypt -lpq -lgd -lm

all: Barchart Scatchart

Barchart: Barchart.o getresults.o
	gcc -o Barchart Barchart.o getresults.o $(LFLAGS)

Scatchart: Scatchart.o getresults.o
	gcc -o Scatchart Scatchart.o getresults.o $(LFLAGS)

Barchart.o: Barchart.cpp results.h
	gcc -c $(CFLAGS) Barchart.cpp

Scatchart.o: Scatchart.cpp results.h
	gcc -c $(CFLAGS) Scatchart.cpp

getresults.o: getresults.cpp results.h
	gcc -c $(CFLAGS) getresults.cpp

install: all
	install Barchart -s /usr/local/bin
	install Scatchart -s /usr/local/bin
