# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.3 from Makefile.am

# Copyright (C) 1994, 1995, 1996, 1997, 1998 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


srcdir = .
top_srcdir = .
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DISTDIR =

pkgdatadir = $(datadir)/libmfl
pkglibdir = $(libdir)/libmfl
pkgincludedir = $(includedir)/libmfl

top_builddir = .

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/ginstall -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = i586-pc-linux-gnu
host_triplet = i586-pc-linux-gnu
CC = gcc
LD = /usr/i586-pc-linux-gnu/bin/ld
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
MAKEINFO = makeinfo
NM = /usr/bin/nm -B
PACKAGE = libmfl
RANLIB = ranlib
VERSION = 2.0.0

SHELL=/bin/sh

SUFFIXES=".c .o"

CFLAGS=-O2 -Wall

lib_LTLIBRARIES = libmfl.la

lib_LIBRARIES = libmfl.a

libmfl_a_SOURCES = binsert.c \
browser.c \
cgi_dir.c \
d_addrec.c \
d_blank.c \
d_close.c \
d_cpystr.c \
d_create.c \
d_getfld.c \
d_getrec.c \
d_open.c \
d_putfld.c \
d_putrec.c \
datump.c \
docbegin.c \
eval_nis.c \
feestdag.c \
forms.c \
hf.c \
mflversion.c \
radio.c \
ref.c \
require_post.c \
scale.c \
sockextr.c \
stripcr.c \
strupr.c \
style.c \
swap4.c \
test_bewoner.c \
weeknr.c

libmfl_la_LDFLAGS = -version-info 0:1:0
libmfl_la_SOURCES = binsert.c \
browser.c \
cgi_dir.c \
d_addrec.c \
d_blank.c \
d_close.c \
d_cpystr.c \
d_create.c \
d_getfld.c \
d_getrec.c \
d_open.c \
d_putfld.c \
d_putrec.c \
datump.c \
docbegin.c \
eval_nis.c \
feestdag.c \
forms.c \
hf.c \
mflversion.c \
radio.c \
ref.c \
require_post.c \
scale.c \
sockextr.c \
stripcr.c \
strupr.c \
style.c \
swap4.c \
test_bewoner.c \
weeknr.c
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES = 
LIBRARIES =  $(lib_LIBRARIES)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I.
CPPFLAGS = 
LDFLAGS = 
LIBS = 
libmfl_a_LIBADD = 
libmfl_a_OBJECTS =  binsert.o browser.o cgi_dir.o d_addrec.o d_blank.o \
d_close.o d_cpystr.o d_create.o d_getfld.o d_getrec.o d_open.o \
d_putfld.o d_putrec.o datump.o docbegin.o eval_nis.o feestdag.o forms.o \
hf.o mflversion.o radio.o ref.o require_post.o scale.o sockextr.o \
stripcr.o strupr.o style.o swap4.o test_bewoner.o weeknr.o
AR = ar
LTLIBRARIES =  $(lib_LTLIBRARIES)

libmfl_la_LIBADD = 
libmfl_la_OBJECTS =  binsert.lo browser.lo cgi_dir.lo d_addrec.lo \
d_blank.lo d_close.lo d_cpystr.lo d_create.lo d_getfld.lo d_getrec.lo \
d_open.lo d_putfld.lo d_putrec.lo datump.lo docbegin.lo eval_nis.lo \
feestdag.lo forms.lo hf.lo mflversion.lo radio.lo ref.lo \
require_post.lo scale.lo sockextr.lo stripcr.lo strupr.lo style.lo \
swap4.lo test_bewoner.lo weeknr.lo
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(CPPFLAGS) $(CFLAGS)
LINK = $(LIBTOOL) --mode=link $(CC) $(CFLAGS) $(LDFLAGS) -o $@
DIST_COMMON =  COPYING INSTALL Makefile.am Makefile.in acconfig.h \
aclocal.m4 config.guess config.h.in config.sub configure configure.in \
install-sh ltconfig ltmain.sh missing mkinstalldirs stamp-h.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = tar
GZIP = --best
DEP_FILES =  .deps/binsert.P .deps/browser.P .deps/cgi_dir.P \
.deps/d_addrec.P .deps/d_blank.P .deps/d_close.P .deps/d_cpystr.P \
.deps/d_create.P .deps/d_getfld.P .deps/d_getrec.P .deps/d_open.P \
.deps/d_putfld.P .deps/d_putrec.P .deps/datump.P .deps/docbegin.P \
.deps/eval_nis.P .deps/feestdag.P .deps/forms.P .deps/hf.P \
.deps/mflversion.P .deps/radio.P .deps/ref.P .deps/require_post.P \
.deps/scale.P .deps/sockextr.P .deps/stripcr.P .deps/strupr.P \
.deps/style.P .deps/swap4.P .deps/test_bewoner.P .deps/weeknr.P
SOURCES = $(libmfl_a_SOURCES) $(libmfl_la_SOURCES)
OBJECTS = $(libmfl_a_OBJECTS) $(libmfl_la_OBJECTS)

all: Makefile $(LIBRARIES) $(LTLIBRARIES) config.h all-local

.SUFFIXES:
.SUFFIXES: ".c .S .c .lo .o .o" .s
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$@ CONFIG_HEADERS= $(SHELL) ./config.status

$(ACLOCAL_M4):  configure.in 
	cd $(srcdir) && $(ACLOCAL)

config.status: $(srcdir)/configure
	$(SHELL) ./config.status --recheck
$(srcdir)/configure: $(srcdir)/configure.in $(ACLOCAL_M4) $(CONFIGURE_DEPENDENCIES)
	cd $(srcdir) && $(AUTOCONF)

config.h: stamp-h
	@:
stamp-h: $(srcdir)/config.h.in $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES= CONFIG_HEADERS=config.h \
	     $(SHELL) ./config.status
	@echo timestamp > stamp-h
$(srcdir)/config.h.in: $(srcdir)/stamp-h.in
$(srcdir)/stamp-h.in: $(top_srcdir)/configure.in $(ACLOCAL_M4) acconfig.h
	cd $(top_srcdir) && $(AUTOHEADER)
	@echo timestamp > $(srcdir)/stamp-h.in

mostlyclean-hdr:

clean-hdr:

distclean-hdr:
	-rm -f config.h

maintainer-clean-hdr:

mostlyclean-libLIBRARIES:

clean-libLIBRARIES:
	-test -z "$(lib_LIBRARIES)" || rm -f $(lib_LIBRARIES)

distclean-libLIBRARIES:

maintainer-clean-libLIBRARIES:

install-libLIBRARIES: $(lib_LIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libdir)
	list='$(lib_LIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(libdir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done
	@$(POST_INSTALL)
	@list='$(lib_LIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(RANLIB) $(DESTDIR)$(libdir)/$$p"; \
	    $(RANLIB) $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done

uninstall-libLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(lib_LIBRARIES)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(libdir)/$$p; \
	done

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

libmfl.a: $(libmfl_a_OBJECTS) $(libmfl_a_DEPENDENCIES)
	-rm -f libmfl.a
	$(AR) cru libmfl.a $(libmfl_a_OBJECTS) $(libmfl_a_LIBADD)
	$(RANLIB) libmfl.a

mostlyclean-libLTLIBRARIES:

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)

distclean-libLTLIBRARIES:

maintainer-clean-libLTLIBRARIES:

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(libdir)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo "$(LIBTOOL)  --mode=install $(INSTALL_DATA) $$p $(DESTDIR)$(libdir)/$$p"; \
	    $(LIBTOOL)  --mode=install $(INSTALL_DATA) $$p $(DESTDIR)$(libdir)/$$p; \
	  else :; fi; \
	done

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  $(LIBTOOL)  --mode=uninstall rm -f $(DESTDIR)$(libdir)/$$p; \
	done

libmfl.la: $(libmfl_la_OBJECTS) $(libmfl_la_DEPENDENCIES)
	$(LINK) -rpath $(libdir) $(libmfl_la_LDFLAGS) $(libmfl_la_OBJECTS) $(libmfl_la_LIBADD) $(LIBS)

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $(SOURCES) $(HEADERS) $(LISP)

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)config.h.in$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags config.h.in $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	-rm -rf $(distdir)
	GZIP=$(GZIP) $(TAR) zxf $(distdir).tar.gz
	mkdir $(distdir)/=build
	mkdir $(distdir)/=inst
	dc_install_base=`cd $(distdir)/=inst && pwd`; \
	cd $(distdir)/=build \
	  && ../configure --srcdir=.. --prefix=$$dc_install_base \
	  && $(MAKE) \
	  && $(MAKE) dvi \
	  && $(MAKE) check \
	  && $(MAKE) install \
	  && $(MAKE) installcheck \
	  && $(MAKE) dist
	-rm -rf $(distdir)
	@echo "========================"; \
	echo "$(distdir).tar.gz is ready for distribution"; \
	echo "========================"
dist: distdir
	-chmod -R a+r $(distdir)
	GZIP=$(GZIP) $(TAR) chozf $(distdir).tar.gz $(distdir)
	-rm -rf $(distdir)
dist-all: distdir
	-chmod -R a+r $(distdir)
	GZIP=$(GZIP) $(TAR) chozf $(distdir).tar.gz $(distdir)
	-rm -rf $(distdir)
distdir: $(DISTFILES)
	-rm -rf $(distdir)
	mkdir $(distdir)
	-chmod 777 $(distdir)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  test -f $(distdir)/$$file \
	  || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	  || cp -p $$d/$$file $(distdir)/$$file; \
	done

DEPS_MAGIC := $(shell mkdir .deps > /dev/null 2>&1 || :)

-include $(DEP_FILES)

mostlyclean-depend:

clean-depend:

distclean-depend:

maintainer-clean-depend:
	-rm -rf .deps

%.o: %.c
	@echo '$(COMPILE) -c $<'; \
	$(COMPILE) -Wp,-MD,.deps/$(*F).P -c $<

%.lo: %.c
	@echo '$(LTCOMPILE) -c $<'; \
	$(LTCOMPILE) -Wp,-MD,.deps/$(*F).p -c $<
	@-sed -e 's/^\([^:]*\)\.o:/\1.lo \1.o:/' \
	  < .deps/$(*F).p > .deps/$(*F).P
	@-rm -f .deps/$(*F).p
info:
dvi:
check: all
	$(MAKE)
installcheck:
install-exec: install-libLIBRARIES install-libLTLIBRARIES
	@$(NORMAL_INSTALL)

install-data: 
	@$(NORMAL_INSTALL)

install: install-exec install-data all
	@:

uninstall: uninstall-libLIBRARIES uninstall-libLTLIBRARIES

install-strip:
	$(MAKE) INSTALL_PROGRAM='$(INSTALL_PROGRAM) -s' INSTALL_SCRIPT='$(INSTALL_PROGRAM)' install
installdirs:
	$(mkinstalldirs)  $(DATADIR)$(libdir) $(DATADIR)$(libdir)


mostlyclean-generic:
	-test -z "$(MOSTLYCLEANFILES)" || rm -f $(MOSTLYCLEANFILES)

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f Makefile $(DISTCLEANFILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
mostlyclean:  mostlyclean-hdr mostlyclean-libLIBRARIES \
		mostlyclean-compile mostlyclean-libtool \
		mostlyclean-libLTLIBRARIES mostlyclean-tags \
		mostlyclean-depend mostlyclean-generic

clean:  clean-hdr clean-libLIBRARIES clean-compile clean-libtool \
		clean-libLTLIBRARIES clean-tags clean-depend \
		clean-generic mostlyclean

distclean:  distclean-hdr distclean-libLIBRARIES distclean-compile \
		distclean-libtool distclean-libLTLIBRARIES \
		distclean-tags distclean-depend distclean-generic clean
	-rm -f config.status
	-rm -f libtool

maintainer-clean:  maintainer-clean-hdr maintainer-clean-libLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-libLTLIBRARIES maintainer-clean-tags \
		maintainer-clean-depend maintainer-clean-generic \
		distclean
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."
	-rm -f config.status

.PHONY: mostlyclean-hdr distclean-hdr clean-hdr maintainer-clean-hdr \
mostlyclean-libLIBRARIES distclean-libLIBRARIES clean-libLIBRARIES \
maintainer-clean-libLIBRARIES uninstall-libLIBRARIES \
install-libLIBRARIES mostlyclean-compile distclean-compile \
clean-compile maintainer-clean-compile mostlyclean-libtool \
distclean-libtool clean-libtool maintainer-clean-libtool \
mostlyclean-libLTLIBRARIES distclean-libLTLIBRARIES \
clean-libLTLIBRARIES maintainer-clean-libLTLIBRARIES \
uninstall-libLTLIBRARIES install-libLTLIBRARIES tags mostlyclean-tags \
distclean-tags clean-tags maintainer-clean-tags distdir \
mostlyclean-depend distclean-depend clean-depend \
maintainer-clean-depend info dvi installcheck install-exec install-data \
install uninstall all installdirs mostlyclean-generic distclean-generic \
clean-generic maintainer-clean-generic clean mostlyclean distclean \
maintainer-clean


all-local: $(CONFIG_HEADER)

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
# DO NOT DELETE

binsert.o: /usr/include/string.h /usr/include/features.h
binsert.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
browser.o: /usr/include/string.h /usr/include/features.h
browser.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
browser.o: /usr/include/stdlib.h /usr/include/sys/types.h
browser.o: /usr/include/bits/types.h /usr/include/time.h
browser.o: /usr/include/endian.h /usr/include/bits/endian.h
browser.o: /usr/include/sys/select.h /usr/include/bits/select.h
browser.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
browser.o: /usr/include/alloca.h /usr/include/unistd.h
browser.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
browser.o: /usr/include/getopt.h
cgi_dir.o: /usr/include/string.h /usr/include/features.h
cgi_dir.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
cgi_dir.o: /usr/include/stdlib.h /usr/include/sys/types.h
cgi_dir.o: /usr/include/bits/types.h /usr/include/time.h
cgi_dir.o: /usr/include/endian.h /usr/include/bits/endian.h
cgi_dir.o: /usr/include/sys/select.h /usr/include/bits/select.h
cgi_dir.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
cgi_dir.o: /usr/include/alloca.h /usr/include/unistd.h
cgi_dir.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
cgi_dir.o: /usr/include/getopt.h config.h
check_user.o: /usr/include/pwd.h /usr/include/features.h
check_user.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
check_user.o: /usr/include/bits/types.h /usr/include/stdio.h
check_user.o: /usr/include/string.h /usr/include/unistd.h
check_user.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
check_user.o: /usr/include/getopt.h /usr/include/crypt.h
check_user_nis.o: /usr/include/string.h /usr/include/features.h
check_user_nis.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
check_user_nis.o: /usr/include/stdio.h /usr/include/stdlib.h
check_user_nis.o: /usr/include/sys/types.h /usr/include/bits/types.h
check_user_nis.o: /usr/include/time.h /usr/include/endian.h
check_user_nis.o: /usr/include/bits/endian.h /usr/include/sys/select.h
check_user_nis.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
check_user_nis.o: /usr/include/sys/sysmacros.h /usr/include/alloca.h
check_user_nis.o: /usr/include/pwd.h /usr/include/crypt.h
check_user_nis.o: /usr/include/rpcsvc/ypclnt.h /usr/include/rpcsvc/yp_prot.h
check_user_nis.o: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
check_user_nis.o: /usr/include/sys/time.h /usr/include/bits/time.h
check_user_nis.o: /usr/include/sys/param.h /usr/include/limits.h
check_user_nis.o: /usr/include/bits/posix1_lim.h
check_user_nis.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
check_user_nis.o: /usr/include/bits/posix2_lim.h /usr/include/linux/param.h
check_user_nis.o: /usr/include/asm/param.h /usr/include/netinet/in.h
check_user_nis.o: /usr/include/stdint.h /usr/include/bits/wordsize.h
check_user_nis.o: /usr/include/bits/socket.h /usr/include/bits/sockaddr.h
check_user_nis.o: /usr/include/asm/socket.h /usr/include/asm/sockios.h
check_user_nis.o: /usr/include/bits/in.h /usr/include/bits/byteswap.h
check_user_nis.o: /usr/include/rpc/xdr.h /usr/include/rpc/auth.h
check_user_nis.o: /usr/include/rpc/clnt.h /usr/include/sys/un.h
check_user_nis.o: /usr/include/rpc/rpc_msg.h /usr/include/rpc/auth_unix.h
check_user_nis.o: /usr/include/rpc/auth_des.h /usr/include/rpc/svc.h
check_user_nis.o: /usr/include/rpc/svc_auth.h /usr/include/rpc/netdb.h
crypt.o: ufc-crypt.h
crypt_util.o: patchlevel.h ufc-crypt.h /usr/include/string.h
crypt_util.o: /usr/include/features.h /usr/include/sys/cdefs.h
crypt_util.o: /usr/include/gnu/stubs.h
d_addrec.o: /usr/include/stdio.h
d_blank.o: /usr/include/stdio.h /usr/include/string.h /usr/include/features.h
d_blank.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
d_close.o: /usr/include/stdio.h /usr/include/stdlib.h /usr/include/features.h
d_close.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
d_close.o: /usr/include/sys/types.h /usr/include/bits/types.h
d_close.o: /usr/include/time.h /usr/include/endian.h
d_close.o: /usr/include/bits/endian.h /usr/include/sys/select.h
d_close.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
d_close.o: /usr/include/sys/sysmacros.h /usr/include/alloca.h
d_cpystr.o: /usr/include/stdio.h /usr/include/stdlib.h
d_cpystr.o: /usr/include/features.h /usr/include/sys/cdefs.h
d_cpystr.o: /usr/include/gnu/stubs.h /usr/include/sys/types.h
d_cpystr.o: /usr/include/bits/types.h /usr/include/time.h
d_cpystr.o: /usr/include/endian.h /usr/include/bits/endian.h
d_cpystr.o: /usr/include/sys/select.h /usr/include/bits/select.h
d_cpystr.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
d_cpystr.o: /usr/include/alloca.h /usr/include/string.h
d_create.o: /usr/include/time.h /usr/include/bits/types.h
d_create.o: /usr/include/features.h /usr/include/sys/cdefs.h
d_create.o: /usr/include/gnu/stubs.h /usr/include/ctype.h
d_create.o: /usr/include/endian.h /usr/include/bits/endian.h
d_create.o: /usr/include/string.h
d_getfld.o: /usr/include/stdio.h /usr/include/string.h
d_getfld.o: /usr/include/features.h /usr/include/sys/cdefs.h
d_getfld.o: /usr/include/gnu/stubs.h
d_getrec.o: /usr/include/stdio.h
d_open.o: /usr/include/stdio.h /usr/include/stdlib.h /usr/include/features.h
d_open.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
d_open.o: /usr/include/sys/types.h /usr/include/bits/types.h
d_open.o: /usr/include/time.h /usr/include/endian.h
d_open.o: /usr/include/bits/endian.h /usr/include/sys/select.h
d_open.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
d_open.o: /usr/include/sys/sysmacros.h /usr/include/alloca.h
d_putfld.o: /usr/include/stdio.h /usr/include/string.h
d_putfld.o: /usr/include/features.h /usr/include/sys/cdefs.h
d_putfld.o: /usr/include/gnu/stubs.h
d_putrec.o: /usr/include/stdio.h
datump.o: /usr/include/time.h /usr/include/bits/types.h
datump.o: /usr/include/features.h /usr/include/sys/cdefs.h
datump.o: /usr/include/gnu/stubs.h
dbcopy.o: /usr/include/stdio.h /usr/include/string.h /usr/include/features.h
dbcopy.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
docbegin.o: /usr/include/stdio.h /usr/include/stdlib.h
docbegin.o: /usr/include/features.h /usr/include/sys/cdefs.h
docbegin.o: /usr/include/gnu/stubs.h /usr/include/sys/types.h
docbegin.o: /usr/include/bits/types.h /usr/include/time.h
docbegin.o: /usr/include/endian.h /usr/include/bits/endian.h
docbegin.o: /usr/include/sys/select.h /usr/include/bits/select.h
docbegin.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
docbegin.o: /usr/include/alloca.h
eval_nis.o: /usr/include/string.h /usr/include/features.h
eval_nis.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
eval_nis.o: /usr/include/stdlib.h /usr/include/sys/types.h
eval_nis.o: /usr/include/bits/types.h /usr/include/time.h
eval_nis.o: /usr/include/endian.h /usr/include/bits/endian.h
eval_nis.o: /usr/include/sys/select.h /usr/include/bits/select.h
eval_nis.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
eval_nis.o: /usr/include/alloca.h /usr/include/pwd.h /usr/include/stdio.h
feestdag.o: /usr/include/time.h /usr/include/bits/types.h
feestdag.o: /usr/include/features.h /usr/include/sys/cdefs.h
feestdag.o: /usr/include/gnu/stubs.h
forms.o: /usr/include/stdio.h /usr/include/string.h /usr/include/features.h
forms.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
mflversion.o: /usr/include/ctype.h /usr/include/features.h
mflversion.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
mflversion.o: /usr/include/bits/types.h /usr/include/endian.h
mflversion.o: /usr/include/bits/endian.h config.h
pie.o: /usr/include/stdio.h /usr/include/stdlib.h /usr/include/features.h
pie.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
pie.o: /usr/include/sys/types.h /usr/include/bits/types.h /usr/include/time.h
pie.o: /usr/include/endian.h /usr/include/bits/endian.h
pie.o: /usr/include/sys/select.h /usr/include/bits/select.h
pie.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
pie.o: /usr/include/alloca.h /usr/include/string.h /usr/include/math.h
pie.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
pie.o: /usr/include/bits/mathcalls.h
plotdb.o: /usr/include/stdlib.h /usr/include/features.h
plotdb.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
plotdb.o: /usr/include/sys/types.h /usr/include/bits/types.h
plotdb.o: /usr/include/time.h /usr/include/endian.h
plotdb.o: /usr/include/bits/endian.h /usr/include/sys/select.h
plotdb.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
plotdb.o: /usr/include/sys/sysmacros.h /usr/include/alloca.h
plotdb.o: /usr/include/string.h plotdb.h
plotit.o: /usr/include/stdlib.h /usr/include/features.h
plotit.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
plotit.o: /usr/include/sys/types.h /usr/include/bits/types.h
plotit.o: /usr/include/time.h /usr/include/endian.h
plotit.o: /usr/include/bits/endian.h /usr/include/sys/select.h
plotit.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
plotit.o: /usr/include/sys/sysmacros.h /usr/include/alloca.h
plotit.o: /usr/include/math.h /usr/include/bits/huge_val.h
plotit.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
plotit.o: /usr/include/stdio.h plotdb.h
radio.o: /usr/include/stdio.h
ref.o: /usr/include/stdio.h
require_post.o: /usr/include/string.h /usr/include/features.h
require_post.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
require_post.o: /usr/include/stdlib.h /usr/include/sys/types.h
require_post.o: /usr/include/bits/types.h /usr/include/time.h
require_post.o: /usr/include/endian.h /usr/include/bits/endian.h
require_post.o: /usr/include/sys/select.h /usr/include/bits/select.h
require_post.o: /usr/include/bits/sigset.h /usr/include/sys/sysmacros.h
require_post.o: /usr/include/alloca.h /usr/include/stdio.h config.h
sockextr.o: /usr/include/stdlib.h /usr/include/features.h
sockextr.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
sockextr.o: /usr/include/sys/types.h /usr/include/bits/types.h
sockextr.o: /usr/include/time.h /usr/include/endian.h
sockextr.o: /usr/include/bits/endian.h /usr/include/sys/select.h
sockextr.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
sockextr.o: /usr/include/sys/sysmacros.h /usr/include/alloca.h
sockextr.o: /usr/include/stdio.h /usr/include/string.h
sockextr.o: /usr/include/sys/socket.h /usr/include/bits/socket.h
sockextr.o: /usr/include/limits.h /usr/include/bits/posix1_lim.h
sockextr.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
sockextr.o: /usr/include/bits/posix2_lim.h /usr/include/bits/sockaddr.h
sockextr.o: /usr/include/asm/socket.h /usr/include/asm/sockios.h
sockextr.o: /usr/include/arpa/inet.h /usr/include/netinet/in.h
sockextr.o: /usr/include/stdint.h /usr/include/bits/wordsize.h
sockextr.o: /usr/include/bits/in.h /usr/include/bits/byteswap.h
sockextr.o: /usr/include/netdb.h /usr/include/rpc/netdb.h
sockextr.o: /usr/include/errno.h /usr/include/bits/errno.h
sockextr.o: /usr/include/linux/errno.h /usr/include/asm/errno.h sockextr.h
sockextr.o: /usr/include/sys/param.h /usr/include/linux/param.h
sockextr.o: /usr/include/asm/param.h /usr/include/unistd.h
sockextr.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
sockextr.o: /usr/include/getopt.h
stripcr.o: /usr/include/string.h /usr/include/features.h
stripcr.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
strupr.o: /usr/include/ctype.h /usr/include/features.h
strupr.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
strupr.o: /usr/include/bits/types.h /usr/include/endian.h
strupr.o: /usr/include/bits/endian.h
style.o: /usr/include/stdio.h /usr/include/string.h /usr/include/features.h
style.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
style.o: /usr/include/stdlib.h /usr/include/sys/types.h
style.o: /usr/include/bits/types.h /usr/include/time.h /usr/include/endian.h
style.o: /usr/include/bits/endian.h /usr/include/sys/select.h
style.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
style.o: /usr/include/sys/sysmacros.h /usr/include/alloca.h
style.o: /usr/include/sys/stat.h /usr/include/bits/stat.h config.h
test_bewoner.o: /usr/include/string.h /usr/include/features.h
test_bewoner.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h config.h
weeknr.o: /usr/include/time.h /usr/include/bits/types.h
weeknr.o: /usr/include/features.h /usr/include/sys/cdefs.h
weeknr.o: /usr/include/gnu/stubs.h /usr/include/stdio.h /usr/include/stdlib.h
weeknr.o: /usr/include/sys/types.h /usr/include/endian.h
weeknr.o: /usr/include/bits/endian.h /usr/include/sys/select.h
weeknr.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
weeknr.o: /usr/include/sys/sysmacros.h /usr/include/alloca.h
