#! /bin/sh

if [ $# == 0 ] ; then
  echo "Argument 1 ontbreekt";
  exit 1
fi

n=$#
for ((j=1;$j<=$n;j=$j+1)); do

i=$1;

id=`psql koersdata -qtAc "select id from rekening where naam='$i';"`
if [ -z "$id" ] ; then
  echo "$i komt niet voor in rekening database"
  exit 1;
fi

echo "entering $i --> - in vertaal"


psql koersdata -qtc "insert into vertaal values ('$i', '-');"
psql koersdata -tc "update vertaal set naam2='-' where naam2='$i';"

echo "removing $i"
psql koersdata -tc "delete from rekening where naam='$i';"

shift

done