#! /bin/sh

(while [ "1" = "1" ] ; do
  IFS="|";
  read naam id rest
  if [ -z "$naam" ] ; then
    break;
  fi
  naam=`echo $naam|perl -e "s/ *$//;" -p`
  echo "$naam: $id"
  psql koersdata -c "insert into koersid select $id,datum,volume,open,hoog,laag,slot from koersen where naam='$naam';"
done ) <nam.inp
