#! /usr/bin/perl -w

use strict;
use Pg;

sub SQLexec {
    my $conn=shift;
    my $cmd = shift;

    print "$cmd\n";
    return $conn->exec($cmd);
}

my $arg1=shift;
my $arg2=shift;
my @row;
my @maand=("JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC");

die "Argument 1 ontbreekt\n" unless $arg1;
die "Argument 2 ontbreekt\n" unless $arg2;

my $conn = Pg::connectdb("dbname=koersdata");

my $result=SQLexec($conn,"select naam2 from vertaal where naam1='$arg2';");
if ($result->ntuples > 0) {
    @row=$result->fetchrow();
    my $x = $row[0];
    die "$arg2 wordt al vertaald in $x. Doe het handmatig\n";
}

$result=SQLexec($conn,"select id from rekening where naam='$arg1';");
die "$arg1 komt niet voor in rekening database\n" if ($result->ntuples ==0);
@row=$result->fetchrow();
my $id1=$row[0];

$result=SQLexec($conn,"select id from rekening where naam='$arg2';");
if ($result->ntuples == 0) {
    SQLexec($conn,"insert into rekening (naam) values ('$arg2');");
    $result=SQLexec($conn,"select id from rekening where naam='$arg2';");
}
@row=$result->fetchrow();
my $id2=$row[0];

$result=SQLexec($conn,"select naam,datum,volume,open,hoog,laag,slot from koers where naam='$arg1';");
if ($result->ntuples > 0) {
    print $result->ntuples," rijen in tabel\n";
    open UIT,">/tmp/iv$$.bsn" or die "Kan uitvoer /tmp/iv$$.bsn niet openen\n";
    while (@row=$result->fetchrow()) {
#	print join(" ",@row),"\n";
	my ($jaar,$maand,$dag)=split("-",$row[1]);
	printf UIT "0/1/%2.2d-%s-%2.2d\r\n",$dag,$maand[$maand-1],$jaar%100;
	printf UIT "9|30|%s|%d|%.2f|%.2f|%.2f|%.2f\r\n",$row[0],$row[2],$row[3],$row[4],$row[5],$row[6];
    }
    close UIT;

    $result=SQLexec($conn,"update koersid set id=$id2 where id=$id1 and not datum in (select d.datum from koersid d where d.id=$id2);");
    print $result->cmdTuples," rijen aangepast\n";
}

SQLexec($conn,"insert into vertaal values ('$arg1','$arg2');");
SQLexec($conn,"update vertaal set naam2='$arg2' where naam2='$arg1';");
SQLexec($conn,"delete from rekening where naam='$arg1'");
