all:
        echo "Nothing to make"
        
install:        croon.js croon.css index.cgi
        install index.cgi /web/www-ssl/croon
        install croon.js /web/www-ssl/croon
        install croon.css /web/www-ssl/croon
        chmod 755 /web/www-ssl/croon/index.cgi
        