#include <stdio.h>
#include <stdlib.h>
#include <www.h>

void print_my_doc_begin(FILE *fid,char *title)
{
  fprintf(fid,"<html>\n");
  fprintf(fid,"<head>\n");
  fprintf(fid,"<title>%s</title>\n",(title[0]=='-'?title+1:title));
  fprintf(fid,"<link rev=made href=\"mailto:mfvl@dds.nl\">\n");
  fprintf(fid,"<!-- Document created with LIBCGI (\"http://wsk.eit.com/wsk/dist/\") -->\n");
  fprintf(fid,"<!-- Program generated by software written by M.F. van Loon -->\n");
  fprintf(fid,"</head>\n");
  if(title[0] != '-')
    fprintf(fid,"<center><h1>%s</h1></center>\n", title);
}

void print_my_doc_end(FILE *fid,char *text,void (*my_doc_end)(FILE *))
{
  char *w;

  fprintf(fid,"<hr>");

  if(my_doc_end != NULL)
    (*my_doc_end)(fid);
  if (text && *text) 

    fprintf(fid,"%s",text);
  else if ((w = getenv("WEBMASTER")) != 0 )
    fprintf(fid,"<address>%s</address>\n", w);
  fprintf(fid,"</body>\n</html>\n");
}

