CC=gcc -O2 -Wall -I/home/mfvl/include

all:  libmfl.a

install: all
	install -m 644 libmfl.a /usr/local/lib

libmfl.a:  weeknr.o scale.o check_user_nis.o d_create.o \
         stripcr.o feestdag.o datump.o binsert.o \
         d_addrec.o d_blank.o d_close.o d_cpystr.o d_getfld.o \
         d_getrec.o d_open.o d_putfld.o d_putrec.o swap4.o mflversion.o \
         strupr.o sockextr.o forms.o ref.o eval_nis.o docbegin.o test_bewoner.o \
         radio.o cgi_dir.o style.o hf.o require_post.o browser.o 
	ar r  libmfl.a weeknr.o check_user_nis.o scale.o d_create.o \
               stripcr.o  feestdag.o datump.o binsert.o \
               d_addrec.o d_blank.o d_close.o d_cpystr.o d_getfld.o \
               d_getrec.o d_open.o d_putfld.o d_putrec.o swap4.o \
               mflversion.o strupr.o sockextr.o forms.o ref.o \
               eval_nis.o docbegin.o test_bewoner.o \
               radio.o cgi_dir.o style.o hf.o require_post.o browser.o 

#tc_emul.o